ROUTINE Math [Type=INC]

#define LeastCommonMultiple		##class(Math.Math).LeastCommonMultiple
#define LCM		##class(Math.Math).LCM

#define GreatestCommonDivisor		##class(Math.Math).GreatestCommonDivisor
#define GCD		##class(Math.Math).GCD

#define Max		##class(Math.Math).Max

#define Min		##class(Math.Math).Min

#define Factorial		##class(Math.Math).Factorial

#define Ceiling ##class(Math.Math).Ceiling

#define Floor ##class(Math.Math).Floor